version: "3.8"

services:
  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - microservices-net
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-net
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  libros-servicio:
    build:
      context: .
      dockerfile: libros-servicio/Dockerfile
    container_name: libros-servicio
    ports:
      - "8081:8081"
    networks:
      - microservices-net
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - CONFIG_SERVER_URI=http://config-server:8888
      - EUREKA_URI=http://eureka-server:8761/eureka

  usuarios-servicio:
    build:
      context: .
      dockerfile: usuarios-servicio/Dockerfile
    container_name: usuarios-servicio
    ports:
      - "8082:8082"
    networks:
      - microservices-net
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - CONFIG_SERVER_URI=http://config-server:8888
      - EUREKA_URI=http://eureka-server:8761/eureka

  pedidos-servicio:
    build:
      context: .
      dockerfile: pedidos-servicio/Dockerfile
    container_name: pedidos-servicio
    ports:
      - "8083:8083"
    networks:
      - microservices-net
    depends_on:
      - config-server
      - eureka-server
      - libros-servicio
      - usuarios-servicio
    environment:
      - CONFIG_SERVER_URI=http://config-server:8888
      - EUREKA_URI=http://eureka-server:8761/eureka
      - USUARIOS_SERVICIO_URL_DOCKER=http://usuarios-servicio:8082/api/usuarios/login

networks:
  microservices-net:
    driver: bridge
