# Etapa 1: Construcción
FROM maven:3.9.9-openjdk-21 AS builder
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src ./src
RUN mvn clean package -DskipTests

# Etapa 2: Producción
FROM eclipse-temurin:21-jdk
WORKDIR /app

# Cambiar el nombre del JAR según el artefacto generado por tu proyecto
COPY --from=builder /app/target/config-server-1.0.0.jar app.jar

EXPOSE 8888
ENTRYPOINT ["java", "-jar", "app.jar"]
