# Nombre del microservicio
spring.application.name=usuarios-servicio
server.port=8082

# Config Server
spring.config.import=optional:configserver:http://localhost:8888

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Base de datos H2
spring.datasource.url=jdbc:h2:mem:usuariosdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# Actuator
management.endpoints.web.exposure.include=*
