spring.application.name=pedidos-servicio

server.port=8083

# URL del endpoint de login del microservicio de usuarios
usuarios.servicio.login.url=http://localhost:8082/api/usuarios/login

# Credenciales para la autenticacion con el microservicio de usuarios
usuarios.servicio.login.usuario=u1@gmail.com
usuarios.servicio.login.contrasena=123456

spring.config.import=optional:configserver:http://localhost:8888

spring.profiles.active=default
