spring.application.name=configserver

server.port=8888

# URL del repositorio
spring.cloud.config.server.git.uri=https://github.com/Oscar-Ed-Gonzalez/libreria-config-repo.git
spring.cloud.config.server.git.default-label=main

# deshabilitar el cache si se requiere mayor dinamismo
spring.cloud.config.server.git.refreshRate=0
